#!/bin/bash

## Author : Aditya Shakya (adi1090x)
## Mail : adi1090x@gmail.com
## Github : @adi1090x
## Reddit : @adi1090x

rofi_command="rofi -theme $HOME/.config/polybar/scripts/themes/powermenu_alt.rasi"

uptime=$(uptime -p | sed -e 's/up //g')

# Options
reboot="  Restart"
shutdown="  Shutdown"
lock="  Lock"
suspend="鈴  Sleep"
logout="  Logout"

# Variable passed to rofi
options="$lock\n$suspend\n$logout\n$reboot\n$shutdown"

chosen="$(echo -e "$options" | $rofi_command -p "System" -dmenu -selected-row 0)"
case $chosen in
    $shutdown)
        systemctl poweroff
        ;;
    $reboot)
        systemctl reboot
        ;;
    $lock)
        xscreensaver-command -lock
        ;;
    $suspend)
        systemctl suspend
        ;;
    $logout)
        loginctl terminate-session $(loginctl --no-pager --no-legend list-sessions | awk "/$USER/{print \$1; exit;}")
        ;;
esac

